development:
  secret_key_base: f654b97e03004b197bcfae39db5f399bba82d8d385619a011247403d10202ca7796896a0d599d3456ec537cafc0fb762f3b1564e02fcf711b668399246d1f334
  host: 'http://localhost:3000'
  github_oauth: # Head to https://github.com/settings/applications/new to generate oauth credentials
    id: <%= ENV['GITHUB_OAUTH_ID'] %>
    secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
    # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  github_api:
    access_token: <%= ENV['GITHUB_API_TOKEN'] %>
  redis_url: redis://localhost

test:
  secret_key_base: 8ee99ee14ff3dea2f83a2c37d1ed5473a4310c73f6e92ef3709f5da67eb3317a4395e2f9fbf0bd985968963bfdb4c068605b4b3515bc4d895d6cb2d690ec6c2d
  host: 'http://localhost:4000'
  github_oauth:
    id: 1d
    secret: s3cr3t
  github_api:
    access_token: t0k3n
  redis_url: redis://localhost

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  github_oauth:
    id: <%= ENV['GITHUB_OAUTH_ID'] %>
    secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
    # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  github_api:
    access_token: <%= ENV['GITHUB_API_TOKEN'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.
